export const quotes = {
  "Technology & Innovation": [
    "Technology is best when it brings people together. – Matt Mullenweg",
    "Innovation distinguishes between a leader and a follower. – Steve Jobs",
    "The great growling engine of change – technology. – Alvin Toffler",
    "The technology you use impresses no one. The experience you create with it is everything. – Sean Gerety",
    "Once a new technology rolls over you, if you’re not part of the steamroller, you’re part of the road. – Stewart Brand",
    "Technology should improve your life… not become your life. – Billy Cox",
    "The future belongs to those who innovate today.",
    "The art challenges the technology, and the technology inspires the art. – John Lasseter",
    "Any sufficiently advanced technology is indistinguishable from magic. – Arthur C. Clarke",
    "Every new technology starts as magic before becoming normal.",
    "Your ability to adapt to technology is your superpower in the digital era.",
    "The best way to predict the future is to invent it. – Alan Kay",
    "You don’t have to build the next big thing. Just build the next better thing.",
    "A truly great innovator doesn’t just ask why—it asks why not?",
    "There are endless possibilities when technology meets imagination.",
    "The best part of innovation is the journey, not just the destination.",
    "Disrupt or be disrupted. The choice is yours in the tech world.",
    "Those who embrace technology are the architects of the future.",
    "True innovation starts with curiosity and a willingness to challenge the status quo.",
    "Every failed experiment is one step closer to a breakthrough.",
    "The best tech solutions simplify complexity, not add to it.",
    "A single idea in technology can change lives.",
    "Inventing the future starts with imagining a better present.",
    "Digital transformation is not about technology—it’s about mindset.",
    "A problem well-defined is a problem half-solved.",
    "The best tech advancements happen when vision meets execution.",
    "In a digital world, creativity is the key to disruption.",
    "Technology is a tool. How you use it defines its impact.",
    "A single breakthrough in technology can change the course of history.",
    "The future of innovation has to include not only the technology but economic viability. – Dennis Muilenburg",
  ],
  "Coding & Development": [
    "Programming isn’t about what you know; it’s about what you can figure out. – Chris Pine",
    "The code you write makes you a programmer. The code you delete makes you a good one. The code you don’t have to write makes you a great one. – Mario Fusco",
    "Every great developer you know got there by solving problems they were unqualified to solve until they actually did it. – Patrick McKenzie",
    "Coding is not just about writing lines of code; it’s about crafting a symphony of logic and creativity.",
    "A bug is not a setback; it’s an opportunity to strengthen your problem-solving skills.",
    "The beauty of programming lies in turning complex problems into elegant solutions.",
    "Dream big, code bigger. The only limits in the IT world are the ones you set for yourself.",
    "Stay curious, for the greatest discoveries often lie hidden in the lines of code.",
    "Persistence and passion are the keys to unraveling the mysteries of technology.",
    "Embrace collaboration, for the best ideas emerge when minds unite in pursuit of innovation.",
  ],
  "Development Lifecycle & IT Leadership": [

    "Success in the IT world comes to those who embrace change and adapt swiftly.",
    "In the digital age, the power to transform lives lies in the hands of IT professionals.",
    "Failures are the building blocks of success. Embrace them, learn from them, and grow stronger. ",
    "In a world driven by technology, the IT professional is the architect of progress.",
    "Stay hungry for knowledge, for the IT landscape is ever-evolving.",
    "The IT professional’s toolbox is not limited to gadgets and software but encompasses endless possibilities.",
    "Your passion for technology is your superpower. Harness it to create something extraordinary.",
    "Innovation knows no boundaries; it thrives on the fearless imagination of IT professionals.",
    "Every bug fixed, every line optimized, brings us closer to a world of seamless technology.",
    "Dare to dream, and then work relentlessly to turn your dreams into digital realities."  
  ],
  "Sky & Limitless Possibilities": [
    "The sky is not the limit; it’s just the beginning of infinite possibilities.",
    "Aim for the sky, but move step by step.",
    "Like the sky, your potential is limitless.",
    "The sky is full of possibilities, just like your future.",
    "Reach for the sky, and if you miss, you’ll land among the stars.",
    "The sky teaches us that change is constant, but beauty remains.",
    "Let your dreams soar as high as the sky.",
    "The sky is a reminder that there’s always more to explore.",
    "Clouds may come and go, but the sky remains vast and open.",
    "The sky is a canvas, and your ambitions are the paint.",
  ],
  "Coding Wisdom": [
    "First, solve the problem. Then, write the code. – John Johnson",
    "Code is like humor—if you have to explain it, it’s bad. – Cory House",
    "Write code as if the next developer maintaining it is a serial killer who knows where you live.",
    "Great coders are great problem solvers first.",
    "Code is poetry, structured yet expressive.",
    "If debugging is the process of removing bugs, then programming must be the process of adding them. – Edsger Dijkstra",
    "Think twice, code once.",
    "A great developer isn’t measured by how much they code but by how well they think.",
    "Code simplicity is brilliance disguised as minimalism.",
    "Bad code can be rewritten. Bad logic needs to be rethought.",
    "Programming teaches you patience, persistence, and problem-solving.",
    "Mastering code isn't just about learning syntax—it’s about thinking systematically.",
    "The cleanest code is the easiest to maintain.",
    "Don’t fear errors; embrace them as lessons in efficiency.",
    "Writing code is like writing a book—the structure makes all the difference.",
    "Great programmers don’t just solve problems; they prevent them.",
    "Coding is a language, and every project tells a story.",
    "Debugging is where patience meets progress.",
    "Write simple, read elegant.",
    "Good code solves problems, but great code prevents them.",
  ],
  "Development Cycle Motivation": [
    "The goal isn’t perfect code—it’s impactful software.",
    "Every feature you build should solve a real problem, not just exist.",
    "Development is an infinite loop of learning, coding, testing, and growing.",
    "The first version is never perfect. Launch, iterate, and improve.",
    "The most important phase in development isn’t coding—it’s thinking.",
    "Small improvements lead to big innovations.",
    "A project’s success isn’t in the code; it’s in the vision behind it.",
    "Speed matters, but so does quality. Find the balance.",
    "Never sacrifice user experience for developer convenience.",
    "Your best project isn’t the one you finish; it’s the one you keep refining.",
  ],
  "Innovation in IT Leadership": [
    "A strong leader doesn’t just manage, they inspire innovation.",
    "The best way to lead an IT team is by embracing constant learning.",
    "In tech, leadership isn’t about control—it’s about enabling growth.",
    "A visionary in IT sees opportunities where others see obstacles.",
    "A great IT team succeeds because of collaboration, not competition.",
    "Decision-making in IT is a mix of logic, instinct, and courage.",
    "The most valuable asset in an IT company isn’t software—it’s people.",
    "Adapting to change in technology isn’t an option; it’s a necessity.",
    "Leadership in tech is about enabling, not controlling.",
    "The best IT leaders foster growth by inspiring curiosity.",
    "In technology, great leadership is measured by impact, not authority.",
    "A great leader sees what others don’t and brings it to life.",
    "Success in IT leadership is about continuous learning and adaptation.",
    "Empower your team, and innovation will follow naturally.",
    "Decision-making in IT leadership is part intuition, part analysis.",
    "The best IT leaders create environments where failure fuels innovation.",
    "Vision in tech leadership is about seeing beyond obstacles to opportunities.",
    "Embrace failure in IT, because every mistake teaches something new.",
    "A product’s success isn’t just measured in users but in its impact.",
  ],
  "Problem-Solving in Tech": [
    "Every problem in tech has a solution—you just have to find it.",
    "The biggest tech breakthroughs come from solving simple problems better.",
    "Don’t fear bugs—embrace them as lessons.",
    "The best fixes in tech are born from deep understanding, not quick patches.",
    "Data without insight is meaningless; analyze before implementing.",
    "User experience matters more than feature count.",
    "Mistakes in tech are stepping stones to efficiency.",
    "The best coding solutions are often the simplest.",
    "Always ask: How can we make this better for the user?",
    "Tech evolves, but human creativity drives the change.",
  ],
  "Development Lifecycle Inspiration": [
    "A well-designed system is one that adapts effortlessly to change.",
    "Features should serve a purpose, not just fill a requirement.",
    "Great apps start with great user experiences.",
    "Software development is a marathon, not a sprint.",
    "Build with future scalability in mind, not just present needs.",
    "Software is never truly finished—only continuously improved.",
    "A great UI feels invisible because it just works.",
    "Prioritize efficiency, but never sacrifice quality.",
    "Every great app solves a problem. What’s yours solving?",
    "Building software is like architecture—it needs a strong foundation.",
  ],
} as const;

export type QuoteCategory = keyof typeof quotes;

export const categories = Object.keys(quotes) as QuoteCategory[];